<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8EPSR7M" failures="1" tests="1" name="TestNGTests.TestNGExpectedExceptions" time="0.051" errors="0" timestamp="5 Sep 2024 12:37:55 GMT">
  <testcase classname="TestNGTests.TestNGExpectedExceptions" name="test" time="0.051">
    <failure message="
Expected exception javaClasses.InsufficientBalanceException but got org.testng.TestException: 
Method TestNGExpectedExceptions.test()[pri:0, instance:TestNGTests.TestNGExpectedExceptions@74bf1791] should have thrown an exception of class javaClasses.InsufficientBalanceException" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception javaClasses.InsufficientBalanceException but got org.testng.TestException: 
Method TestNGExpectedExceptions.test()[pri:0, instance:TestNGTests.TestNGExpectedExceptions@74bf1791] should have thrown an exception of class javaClasses.InsufficientBalanceException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: org.testng.TestException: 
Method TestNGExpectedExceptions.test()[pri:0, instance:TestNGTests.TestNGExpectedExceptions@74bf1791] should have thrown an exception of class javaClasses.InsufficientBalanceException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1512)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 16 more
]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- TestNGTests.TestNGExpectedExceptions -->
